# Generated by Django 5.1.4 on 2025-04-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/')),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'colections',
                'ordering': ('name',),
            },
        ),
    ]
