# Generated by Django 5.1.4 on 2025-04-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collections',
            options={'ordering': ('name',), 'verbose_name': 'collection', 'verbose_name_plural': 'collections'},
        ),
    ]
