# Generated by Django 5.1.4 on 2025-04-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_collections_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='shop.collections'),
        ),
    ]
