# Generated by Django 5.1.4 on 2025-01-10 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('0', 'Ordered'), ('1', 'Recieved'), ('2', 'Processed'), ('3', 'Sent')], default='0', max_length=20),
        ),
    ]
