# Generated by Django 5.1.4 on 2025-01-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Ordered'), (1, 'Recieved'), (2, 'Processed'), (3, 'Sent')], default=0),
        ),
    ]
