# Generated by Django 5.1.4 on 2025-04-16 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_status'),
        ('shop', '0007_remove_product_thumbnail_category_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='brand_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='shop.product'),
        ),
    ]
