# Generated by Django 5.1.4 on 2025-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_brand_name_orderitem_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='category_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
