# Generated by Django 5.1.4 on 2025-04-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderitem_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=225)),
                ('customer_name', models.CharField(max_length=225)),
                ('customer_email', models.CharField(max_length=225)),
                ('customer_phone', models.CharField(max_length=225)),
                ('prodduct', models.CharField(max_length=225)),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.CharField(max_length=225)),
                ('refunded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='has_refund',
            field=models.BooleanField(default=False),
        ),
    ]
