# Generated by Django 5.1.4 on 2025-04-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_refund_order_has_refund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='prodduct',
            new_name='product',
        ),
    ]
