# Generated by Django 5.1.4 on 2025-04-22 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_prodduct_refund_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='order_id',
        ),
        migrations.AddField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds', to='order.order'),
        ),
    ]
