# Generated by Django 5.1.4 on 2025-01-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategory',
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='BlogPost',
        ),
    ]
